formatter: markdown

sort:
  enabled: true
  by: required


output:
  file: "README.md"
  mode: replace
  # For the Pre-Commit to be happy with its newline
  template: "{{ .Content }}\n"


content: |-
  # Vault/OpenBao setup for GatePlane
  ![License: ElasticV2](https://img.shields.io/badge/ElasticV2-green?style=flat-square&label=license&cacheSeconds=3600&link=https%3A%2F%2Fwww.elastic.co%2Flicensing%2Felastic-license)

  This Terraform module enables a Vault/OpenBao instance to use GatePlane.

  * It enables [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS)
  and [Content Security Policy (CSP) for IFrames](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy/frame-ancestors)
  to allow browser access from [`https://app.gateplane.io`](https://app.gateplane.io) (domain can be changed).

  * It can register all GatePlane plugins to the Vault/OpenBao instance, so they can be recognised by the UI.


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}


  ## License

  This project is licensed under the [Elastic License v2](https://www.elastic.co/licensing/elastic-license).

  This means:

  - ✅ You can use, fork, and modify it for **yourself** or **within your company**.
  - ✅ You can submit pull requests and redistribute modified versions (with the license attached).
  - ❌ You may **not** sell it, offer it as a paid product, or use it in a hosted service (e.g., SaaS).
  - ❌ You may **not** re-license it under a different license.

  In short: You can use and extend the code freely, privately or inside your business - just don’t build a business around it without our permission.
  [This FAQ by Elastic](https://www.elastic.co/licensing/elastic-license/faq) greatly summarizes things.

  See the [`./LICENSES/Elastic-2.0.txt`](./LICENSES/Elastic-2.0.txt) file for full details.
